export const TOP_TECHNOLOGIES = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Dart",
  "R",
  "Scala",
  "Perl",
  "Haskell",
  "Lua",
  "MATLAB",
  "Elixir",
  "Erlang",
  "Clojure",
  "F#",
  "Julia",
  "Objective-C",
  "Visual Basic .NET",
  "Bash",
  "PowerShell",
  "SQL",
  "HTML",
  "CSS",
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "ASP.NET Core",
  "Laravel",
  "Ruby on Rails",
  "Tailwind CSS",
  "Bootstrap",
  "Redux",
  "GraphQL",
  "gRPC",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "AI Agents",
  "Prompt Engineering",
  "Computer Vision",
  "Natural Language Processing",
  "Generative AI",
  "LangChain",
  "LlamaIndex",
  "n8n",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "Linux",
  "Git",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "Supabase",
  "Prisma",
  "SQL Server",
  "Oracle Database",
  "SQLite",
  "Apache Kafka",
  "Data Structures and Algorithms",
  "System Design",
  "Operating Systems",
  "Computer Networks",
  "Cybersecurity",
  "AWS",
  "Azure",
  "Google Cloud",
  "Pandas",
  "NumPy",
  "PyTorch",
  "TensorFlow",
  "OpenCV",
  "Unity",
  "Unreal Engine",
  "React Native",
  "Flutter"
] as const;
